### ISSUE TITLE
Update F-Droid version

### ISSUE THREAD

**Issue by quantizzed** [deep-gaurav/MusicPiped#33]
The F-Droid version is stuck at v. 0.2.3-beta. Any plans to update to keep up with the Play Store version?

**Comment by deep-gaurav** [comment]
I'm removing ads and preparing a desktop version, will update this weekend,.

**Comment by deep-gaurav** [comment]
one more problem is that the new version uses invidious instead of newpipe, which might not fit for F-Droid, so i'm trying to put newpipextractor back for f-droid version

**Comment by ArmeF97** [comment]
Why invidious? Is it better than newpipe? @deep-gaurav

**Comment by deep-gaurav** [comment]
Invidious does provide more streams and more thumbnails, and scraping is done on server side so just a request is sent to api to receive json from server instead of downloading whole page and scraping it, which newpipe did, and took long time..

**Comment by deep-gaurav** [comment]
Released on Github, F-Droid should give update in a few days

**Comment by deep-gaurav** [comment]
closing this issue

**Comment by deep-gaurav** [comment]
Fdroid might not give update for new version,
New app is built on flutter and build process is different, so fdroid build might fail, can anyone help out with it?
We need to modify fdroid's yml so that it builds from android subdirectory in source instead of source directoey

**Comment by ArmeF97** [comment]
I don't know this, I'm sorry

**Comment by relan** [comment]
Hi,

F-Droid maintainer here. Could you post detailed instructions how to build v1.0.0? I'm stuck at

```
$ gradle assembleRelease

FAILURE: Build failed with an exception.

* Where:
Build file '/home/fdroid/fdroiddata/build/deep.ryd.rydplayer/android/app/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':app'.
> Flutter SDK not found. Define location with flutter.sdk in the local.properties file.
```

**Comment by deep-gaurav** [comment]
Hi @relan ,
Thanks for contacting, This app is now made with flutter so building apk needs to have flutter SDK in system.
Which is essentially downloading sdk and adding flutter/bin to PATH, 
https://flutter.io/docs/get-started/install 

Let me know if it works and I can help better

**Comment by relan** [comment]
Didn't work for me, unfortunately:

```sh
$ cd android/app
$ gradle clean

FAILURE: Build failed with an exception.

* Where:
Script '/home/fdroid/fdroiddata/build/srclib/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 193

* What went wrong:
A problem occurred configuring project ':path_provider'.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':path_provider' of type org.gradle.api.Project.
   > Could not find method debugProvided() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

I'm using flutter 1.0.0 and gradle 4.10.2 on Debian 9.7 amd64.

**Comment by deep-gaurav** [comment]
I see it seems to be like an error in a flutter module path_provider.
 It looks like path_provider is not being downloaded from pub. This is automatically done when using flutter method to build APK, but I guess not when using gradle directly.

If you've flutter installed, running

```flutter build apk``` in project directory should build apk

**Comment by deep-gaurav** [comment]
Also just to mention, the packages downloaded from pub by flutter are sources themselves and not binary or compiled projects, so it should still be compatible with F-Droid Policy :)

**Comment by relan** [comment]
`flutter packages get` did the trick. Updated in https://gitlab.com/fdroid/fdroiddata/commit/2ca3d88cbd26f453077a53b3265f22dedb511fa9.

The only problem was that build.gradle is missing `maven { url "https://jitpack.io" }`, so Gradle couldn't find NewPipeExtractor. Please fix this in a future version (I added a hack for now). Also `jcenter{ url "https://jcenter.bintray.com/"}` looks odd.

**Comment by deep-gaurav** [comment]
jcenter bintray is needed to download gradle build in prepare script of flutter build which i need for testing, no additional binaries are downloaded

 ff8368c  adds jitpack repo so closing this issue
Thank You

**Comment by dimqua** [comment]
@deep-gaurav did you drop Invidious support?

**Comment by relan** [comment]
> jcenter bintray is needed to download gradle build in prepare script of flutter build which i need for testing, no additional binaries are downloaded

I meant the syntax:

    jcenter{ url "https://jcenter.bintray.com/"}

It's usually

    jcenter()

or

    maven { url "https://jcenter.bintray.com/" }

:)

**Comment by deep-gaurav** [comment]
@dimqua not yet, invidious is used first but if it fails newpipe is used. But I'm thinking to remove invidious as I couldn't find localisation support in it. And for some reason it seems to be getting slower (or maybe just my network 😅)

**Comment by deep-gaurav** [comment]
@relaj got it, it was pregenerated by flutter so didn't looked., I'll see

**Comment by omarroth** [comment]
I'm not sure what you mean by localization support, but I'd like to address any issues you're having with the Invidious API.

If you want you can discuss them here, or hop on the [Invidious Matrix Server](https://riot.im/app/#/room/#invidious:matrix.org) so I can help you use it in your project.

**Comment by deep-gaurav** [comment]
Hi @omarroth , By localisation I meant I couldn't find any parameter in search API for country to search with, I think this could also be reason for #39 where some videos weren't found even after they existed on YouTube

**Comment by omarroth** [comment]
Added support for `&region=` in `/api/v1/search` with [`a7b7982`](https://github.com/omarroth/invidious/commit/a7b79824de7fdcadd5139a1e5ccf7870c194b305).

`/api/v1/search`, `/api/v1/trending`, and `/api/v1/videos` support the `region=REGION` param. The following regions are supported for `search` and `videos`: AE, BD, BR, CA, CD, CN, DE, EG, ES, FR, GB, ID, IN, IT, JP, KR, MX, PH, PK, RU, TH, TR, VN. You can see an example [here](https://invidio.us/api/v1/search?q=football&region=DE&pretty=1).

`trending` should support all regions supported by YouTube.

The default region is US and does not need to be specified.

Requests to `videos` and `search` are proxied by Invidious in order to work correctly. See my comment in [#92](https://github.com/omarroth/invidious/issues/92#issuecomment-443517338) for more info, as there's still room for improvement.

For `videos` and `search`, I would consider the region param a "hint" for where to pull from first. Invidious will fallback on the region where it is hosted (US) if it is not able to proxy the request.

I hope all that is helpful.

I'm working on speeding up response times as much as possible. If there are any endpoints you would like to be prioritized let me know. Feel free to hop on the matrix server as mentioned above, or send me an email at omarroth@protonmail.com .

**Comment by dimqua** [comment]
@deep-gaurav @relan the latest version (1.0.5) still isn't on F-Droid: https://f-droid.org/packages/deep.ryd.rydplayer/

**Comment by relan** [comment]
@dimqua, each new version has to be added manually because of dynamic versionName: https://github.com/deep-gaurav/MusicPiped/blob/v1.0.5/android/app/build.gradle#L46

**Comment by dimqua** [comment]
@deep-gaurav is it possible to use a constant _versionName_?

**Comment by deep-gaurav** [comment]
Yeah that's no problem I'll use a constant version name from next version

**Comment by relan** [comment]
> I'll use a constant version name from next version

This would be awesome. Please ping me once you do this and I'll enable automatic updates.

**Comment by deep-gaurav** [comment]
@relan from 861b7ee on constant version name is used, new update released too, You can enable automatic updates

**Comment by relan** [comment]
Added 1.0.6 in [6db8989](https://gitlab.com/fdroid/fdroiddata/commit/6db8989f3784303c06fd3a7739a83be40ae337f1).

fdroidserver misinterprets this part of [build.gradle](https://github.com/deep-gaurav/MusicPiped/blob/v1.0.6/android/app/build.gradle) when checks for updates:
```groovy
def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}
```
Could you remove this code? It's unused anyway. (No rush, we can wait.)

**Comment by deep-gaurav** [comment]
@relan removed those unused declaration in commit 1ad05e8

**Comment by relan** [comment]
Added 1.0.7 and enabled autoupdates in [c36b7f9](https://gitlab.com/fdroid/fdroiddata/commit/c36b7f9a88b513522e57802eae195d33d95ea64b). Thanks!

**Comment by Gitoffthelawn** [comment]
F-Droid version is now stuck at v1.20 - Can it be updated?

Does this issue need to be reopened?

**Comment by deep-gaurav** [comment]
I didn't knew, can't say, I've released it on GitHub it should have updated on fdroid

**Comment by Gitoffthelawn** [comment]
Hmmm... do you have any contacts at F-Droid that might be able to tell you what's going on?

**Comment by deep-gaurav** [comment]
A report is generated by fdroid builder when it tries to build online, I'll have to check how to find it, 

Will open issue for now.
If there is no mistake in that report on app side we can open issue on fdroid repo

**Comment by relan** [comment]
Looks like 1ad05e8 never got into `master`, so the reason why F-Droid can't find updates is the same. I [submitted a fix](https://gitlab.com/fdroid/fdroidserver/merge_requests/649) to fdroidserver but it can take ages to merge and deploy.

I built v2.0.3 but it does not work on my Android 8.1 tablet: views are empty, search never finishes. On start I get this:

```
06-13 20:28:06.661   441   462 I ActivityManager: Displayed deep.ryd.rydplayer/deep.ryd.MainActivity: +282ms
06-13 20:28:06.868 16606 16821 I flutter : musicpiped: Dart Handler Ready
06-13 20:28:06.906 16606 16821 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s)
06-13 20:28:06.906 16606 16821 E flutter : #0      _StringBase.+ (dart:core-patch/string_patch.dart:260)
06-13 20:28:06.906 16606 16821 E flutter : #1      new AudioPlayer..<anonymous closure> (package:musicpiped_pro/playerService.dart:45)
06-13 20:28:06.906 16606 16821 E flutter : #2      _rootRunUnary (dart:async/zone.dart:1132)
06-13 20:28:06.906 16606 16821 E flutter : #3      _CustomZone.runUnary (dart:async/zone.dart:1029)
06-13 20:28:06.906 16606 16821 E flutter : #4      _FutureListener.handleValue (dart:async/future_impl.dart:126)
06-13 20:28:06.906 16606 16821 E flutter : #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639)
06-13 20:28:06.906 16606 16821 E flutter : #6      Future._propagateToListeners (dart:async/future_impl.dart:668)
06-13 20:28:06.906 16606 16821 E flutter : #7      Future._complete (dart:async/future_impl.dart:473)
06-13 20:28:06.906 16606 16821 E flutter : #8      _SyncCompleter.complete (dart:async/future_impl.dart:51)
06-13 20:28:06.906 16606 16821 E flutter : #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28)
06-13 20:28:06.906 16606 16821 E flutter : #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294)
06-13 20:28:06.906 16606 16821 E flutter : #11     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:0)
06-13 20:28:06.906 16606 16821 E flutter : <asynchronous suspension>
06-13 20:28:06.906 16606 16821 E flutter : #12     new AudioPlayer. (package:musicpiped_pro/playerService.dart:45)
06-13 20:28:06.906 16606 16821 E flutter : #13     init:player (package:musicpiped_pro/main.dart:41)
06-13 20:28:06.906 16606 16821 E flutter : #14     get:player (package:musicpiped_pro/main.dart:41)
06-13 20:28:06.906 16606 16821 E flutter : #15     MyHomePageState.initState (package:musicpiped_pro/main.dart:197)
06-13 20:28:06.906 16606 16821 E flutter : #16     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3943)
06-13 20:28:06.906 16606 16821 E flutter : #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814)
06-13 20:28:06.906 16606 16821 E flutter : #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053)
06-13 20:28:06.906 16606 16821 E flutter : #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2856)
06-13 20:28:06.906 16606 16821 E flutter : #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973)
06-13 20:28:06.906 16606 16821 E flutter : #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053)
06-13 20:28:06.906 16606 16821 E flutter : #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2856)
06-13 20:28:06.906 16606 16821 E flutter : #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847)
06-13 20:28:06.906 16606 16821 E flutter : #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3657)
06-13 20:28:06.906 16606 16821 E flutter : #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819)
06-13 20:28:06.906 16606 16821 E flutter : #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814)
06-13 20:28:06.906 16606 16821 E flutter : #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053)
06-13 20:28:06.906 16606 16821 E flutter : #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2856)
06-13 20:28:06.906 16606 16821 E flutter : #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973)
06-13 20:28:06.906 16606 16821 E flutter : #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053)
06-13 20:28:06.906 16606 16821 E flutter : #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2856)
06-13 20:28:06.906 16606 16821 E flutter : #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973)
06-13 20:28:06.906 16606 16821 E flutter : #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053)
06-13 20:28:06.906 16606 16821 E flutter : #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2856)
06-13 20:28:06.906 16606 16821 E flutter : #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973)
06-13 20:28:06.906 16606 16821 E flutter : #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053)
06-13 20:28:06.906 16606 16821 E flutter : #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2856)
06-13 20:28:06.906 16606 16821 E flutter : #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973)
06-13 20:28:06.906 16606 16821 E flutter : #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053)
06-13 20:28:06.906 16606 16821 E flutter : #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2856)
06-13 20:28:06.906 16606 16821 E flutter : #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847)
06-13 20:28:06.906 16606 16821 E flutter : #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3657)
06-13 20:28:06.906 16606 16821 E flutter : #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819)
06-13 20:28:06.906 16606 16821 E flutter : #44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3961)
06-13 20:28:06.906 16606 16821 E flutter : #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814)
06-13 20:28:06.906 16606 16821 E flutter : #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053)
06-13 20:28:06.906 16606 16821 E flutter : #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2856)
06-13 20:28:06.906 16606 16821 E flutter : #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847)
06-13 20:28:06.906 16606 16821 E flutter : #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3657)
06-13 20:28:06.906 16606 16821 E flutter : #50     Com
06-13 20:28:06.956 16606 16821 I flutter : readingDB
06-13 20:28:06.956 16606 16821 I flutter : Instance of 'Future<dynamic>'
06-13 20:28:06.957 16606 16821 I flutter : Completed
06-13 20:28:06.959 16606 16821 I flutter : 0
```

Tried Flutter 1.6.7 and 1.7.3, seems to make no difference. Any ideas?

**Comment by deep-gaurav** [comment]
The error is not related to search, it looks like a player related error. Which will not effect search at all, if you're just seeing a circular progress bar all time it could be that the request is failing, I have not added an error handler.

Can you try Changing invidious instance url to something else and retry.

That being said I'll add an error handler for search in next version

**Comment by relan** [comment]
> if you're just seeing a circular progress bar all time it could be that the request is failing

Yep.

> Can you try Changing invidious instance url to something else and retry.

Tried vid.wxzm.sx, invidious.kabi.tk and invidiou.sh (from [this list](https://github.com/omarroth/invidious/wiki/Invidious-Instances))---search works with neither of them.

**Comment by deep-gaurav** [comment]
@relan 
I improved search and it'll now show error if fails with retry can you check now and report error it projects if it does i.e 
Thanks

**Comment by relan** [comment]
Search works in 2.0.5 but playback never starts.

**Comment by deep-gaurav** [comment]
Can you monitor the logcat with search/tag "musicpiped" It should output
getNewpipe Url and response codes.

From some time all url received by newpipe are giving 403 error specially
in music videos.

If you're trying to play from any official channel, try out video from non
official ones.

I'm trying to figure out some way to fix it

**Comment by ArmeF97** [comment]
Fdroid still 1.2.0 version

**Comment by deep-gaurav** [comment]
Sorry for late reply, @ArmeF97
Can you create an issue on fdroid repo and link it here?
Since app is completely ok from what ik

**Comment by ArmelliniFederico** [comment]
Before that, is it still 1.2.0 on fdroid for you? https://f-droid.org/en/packages/deep.ryd.rydplayer/
Here it says 1.2.0

Confirm that before everything

**Comment by deep-gaurav** [comment]
It does say 1.2.0 I do not know why, neither can I find build log

**Comment by esmoak** [comment]
Commented on this thread:

https://gitlab.com/fdroid/rfp/issues/758

Not sure if that's the best way to bring this to the forefront or if it needs a brand new issue.
