### ISSUE TITLE
MusicPiped crashes on launch.

### ISSUE THREAD

**Issue by linuxhelper** [deep-gaurav/MusicPiped#75]
Hi, MusicPiped crashes on launch for the past few weeks or so. I uninstalled the F-Droid version and replaced it with the Yalp store version - no change. Cleared the storage. It launches a crash report - no email address. LineageOS 15.1 on a Nexus 5x.

///////////
java.lang.RuntimeException: Unable to create service me.devsilver.musicpiped.PlayerService: java.lang.RuntimeException: Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3349)
	at android.app.ActivityThread.-wrap4(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.RuntimeException: Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3
	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:411)
	at android.media.audiofx.Equalizer.<init>(Equalizer.java:139)
	at me.devsilver.musicpiped.PlayerService.onCreate(PlayerService.java:164)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)
	... 8 more

**Comment by deep-gaurav** [comment]
Thanks for the bug report

It looks like Equalizer is not able to start. I will add an exception handler and disable Equalizer if it doesn't start.
Can you try clearing data and I think on lineage os there is a built in Equalizer it might be preventing app's Equalizer from starting, can you try disabling it first and launching app.

**Comment by linuxhelper** [comment]
I updated LineageOS last night - and so far the app is up and running again.

**Comment by deep-gaurav** [comment]
I think it was issue with Lineage OS then, I'll still add a exception handler for equalizer. Closing issue
